server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    mysql:
      username: root
      password: m+7jP@9QvE
      url: jdbc:mysql://117.72.127.57:13306/ai-agent-station-study?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: MySQLHikariPool
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    pgvector:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: sws511+0.
      url: jdbc:postgresql://117.72.127.57:5432/vector_store_openai
      hikari:
        pool-name: PostgresHikariPool
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
  ai:
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-jNwXKo0k8fXUJVwd8b05841880D041F89b1d8949C2AfBeA4
#  ai:
#    openai:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      api-key: ${DASHSCOPE_API_KEY}

# MyBatis 配置【如需使用记得打开】
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml